/* The MIT License (MIT)

Copyright (c) 2016 Gene Diaz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE. */

const ukr = [
  'а',
  'авжеж',
  'адже',
  'аж',
  'але',
  'ані',
  'б',
  'без',
  'би',
  'бо',
  'був',
  'була',
  'були',
  'було',
  'бути',
  'більш',
  'в',
  'вам',
  'вас',
  'весь',
  'вже',
  'вздовж',
  'ви',
  'від',
  'вниз',
  'внизу',
  'вона',
  'вони',
  'воно',
  'все',
  'всередині',
  'всіх',
  'від',
  'він',
  'да',
  'давай',
  'давати',
  'де',
  'десь',
  'дещо',
  'для',
  'до',
  'є',
  'ж',
  'же',
  'з',
  'за',
  'завжди',
  'замість',
  'і',
  'із',
  'інших',
  'її',
  'їй',
  'їм',
  'їх',
  'й',
  'його',
  'йому',
  'коли',
  'ледве',
  'лиш',
  'майже',
  'мене',
  'мені',
  'ми',
  'між',
  'мій',
  'мною',
  'мов',
  'моєї',
  'моє',
  'може',
  'мої',
  'моїх',
  'моя',
  'на',
  'над',
  'навколо',
  'навіть',
  'нам',
  'нами',
  'нас',
  'наче',
  'наш',
  'не',
  'неї',
  'нема',
  'немов',
  'неначе',
  'нею',
  'ним',
  'ними',
  'них',
  'ні',
  'ніби',
  'ніщо',
  'нього',
  'о',
  'ось',
  'от',
  'отже',
  'отож',
  'під',
  'по',
  'поза',
  'про',
  'під',
  'сам',
  'свій',
  'свої',
  'своя',
  'свою',
  'себе',
  'собі',
  'та',
  'там',
  'так',
  'такий',
  'також',
  'твій',
  'твої',
  'твоя',
  'те',
  'тебе',
  'ти',
  'ті',
  'тільки',
  'то',
  'тобою',
  'тобто',
  'тоді',
  'тож',
  'той',
  'тощо',
  'тут',
  'у',
  'хіба',
  'хоч',
  'хоча',
  'це',
  'цей',
  'ці',
  'ця',
  'чи',
  'чого',
  'ще',
  'що',
  'щоб',
  'щось',
  'я',
  'як',
  'який',
  'якої'
]
export { ukr }
